language: php

matrix:
  include:
    - php: '7.2'
      env: ANALYSIS='true'
    - php: '7.3'
    - php: '7.4'
    - php: '8.0'
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  - flags="--ansi --no-interaction --no-suggest"
  - composer install $flags

script:
  - if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpunit --coverage-clover=coverage.xml ; else vendor/bin/phpunit ; fi

after_success:
  - if [[ "$ANALYSIS" == 'true' ]]; then bash <(curl -s https://codecov.io/bash) ; fi
